# Generated by Django 5.0.6 on 2024-07-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depot', '0002_alter_barang_brg_gambar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='brg_nama',
            field=models.CharField(max_length=100),
        ),
    ]
