# Generated by Django 5.0.6 on 2024-07-04 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bahasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bhs_buku', models.CharField(max_length=50)),
                ('bhs_ket', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Jenis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jns_buku', models.CharField(max_length=50)),
                ('jns_ket', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brg_kode', models.CharField(max_length=8)),
                ('brg_nama', models.CharField(max_length=50)),
                ('brg_stok', models.IntegerField()),
                ('brg_harga', models.BigIntegerField()),
                ('brg_gambar', models.CharField(blank=True, max_length=200)),
                ('brg_waktuposting', models.DateTimeField(auto_now_add=True)),
                ('brg_bahasa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='depot.bahasa')),
                ('brg_jenis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='depot.jenis')),
            ],
        ),
    ]
