# Generated by Django 5.0.6 on 2024-07-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='brg_gambar',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
